### ISSUE TITLE
Provide template helpers to optimize and inject URLs for all types of front-end resources

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/optimizer#34]
Currently, there is no easy way for a static resource (such as a favicon) to go through the optimizer and for the resulting URL to be injected into the final HTML output.

For example:

```html
<link rel="shortcut icon" href="/common/favicon.ico">
```

Ideally, we would like to see output similar to the following:

```html
<link rel="shortcut icon" href="/static/favicon-a46d0c.ico">
```

Proposals:

__Option 1:__
```html
<link rel="shortcut icon" optimizer-href="/common/favicon.ico">
```

__Option 2:__

```html
<optimizer-resource path="/common/favicon.ico" var="favicon"/>
<link rel="shortcut icon" href="${favicon.url}">
```

Initial discussion: https://groups.google.com/forum/#!msg/raptorjs/B8l86j90ROY/6YsDPaNuSdcJ

**Comment by philidem** [comment]
Option 2 would work very well for me. Good proposal!

**Comment by patrick-steele-idem** [comment]
Alright, I'll take this issue then.

**Comment by patrick-steele-idem** [comment]
Feature added. The following is now supported:

```html
<optimizer-resource path="/common/favicon.ico" var="favicon"/>
<link rel="shortcut icon" href="${favicon.url}">
```

Please see the following docs: https://github.com/raptorjs/optimizer/blob/master/taglib-marko.md#optimizer-resource

New version published: `optimizer@1.5.8`

**Comment by schetnikovich** [comment]
I also agree with @philidem that **Option 2** is prefered if we are forced to select only single solution, because of better flexibility. In the same time, I think that **Option 1** is important for Optimizer and Marko marketing purposes :) It advertises Marko's benefits of being HTML-based template language!

I have related question about `<optimizer-img />`. What are the functional differences between the following two snippets?

1) 
```html
<optimizer-resource path="src/common/image.png" var="image"/>
<img src="${image.url}">
```
2) 
```html
<optimizer-img src="src/common/image.png">
```

Maybe with **Option 1** it is possible instead of special `<optimizer-img />` tag simply write:

```html
<img optimizer-src="src/common/image.png">
```

If we need to distinguish type or additional params of such dependency we can apply the same heuristic that is currently in place and distinguishes, for instance, JS dependency from CSS dependency by file extension. For explicit options we can use:

```html
<img optimizer-src="src/common/image.png" optimizer-type="png">
```

It introduces possible name clash, so it needs to be revisited.

We can either scan HTML tags for all `optimizer-*` attributes (flexible, but debatable), or simply create all possible attributes: `optimizer-src`, `optimizer-href`, `optimizer-poster` (poster attribute is possible in HTML5 `video` tag) etc.

I'm writing all of this because of good life. Nothing of what I mention above is critical or even important.  

Thank you for implementing Option 2! This is even more than I need.

**Comment by patrick-steele-idem** [comment]
Hi @schetnikovich, 

The following are _currently_ equivalent:

```html
<optimizer-resource path="src/common/image.png" var="image"/>
<img src="${image.url}">
```

<hr>

```html
<optimizer-img src="src/common/image.png">
```

However, they may not be equivalent in the future. There were talks of possibly reading the image file and also setting the `width` and `height` attributes (if not specified). In the future, we might want to consider updating the `<optimizer-img>` tag to allow the following:

_Input:_

```html
<optimizer-img src="src/common/image.png">
```

_Output:_

```html
<img src="/static/image-abcd0123.png" width="32" height="32">
```

That's the reason for making `<optimizer-img>` a special tag. We already have a separate plugin (see https://github.com/raptorjs/optimizer-image) for getting more details about images (width, height and optimized URL), but it does not have an associated taglib.

You make good points regarding adding support for `optimizer-*`. I'm less concerned about the performance penalty of looking for all `optimizer-*` attributes and more concerned that the behavior is not intuitive. If I were just looking at the following template with no knowledge:

```html
<img optimizer-src="src/common/image.png" optimizer-type="png">
```

I am not sure it would be intuitive to expect the `optimizer-src` attribute to be renamed to "src" and for the value of the `src` to be treated as a resource path that results in the referenced resource getting optimized and the attribute value being replaced with the resulting optimized URL.

At the same time, once you learn what the `optimizer-*` attributes mean then it is pretty obvious. There's also the concern about possibly introducing naming conflicts, but it seems very unlikely that anyone would happen to prefix an attribute with `optimizer-`.

I think starting with the more general solution that has been implemented is a good start, but I am definitely still open to also supporting Option 1 (supporting `optimizer-*` attributes). I think this is a good discussion and will create a new Github issue to further discuss Option 1 as another feature enhancement.

**Comment by schetnikovich** [comment]
I see now that **Option 1** is a problematic solution. And I understand now why we need special `optimizer-img` tag. Thank you for thorough explanation! 

Another problem is a possibility of multiple resource attributes in the single tag, and problem of additional params configuration. For instance: 

```html
<tag optimizer-src="./some/file.gif" optimizer-href="./some/another/file.less" optimizer-type="less" />
```

There is no way to say unambiguously what resource has `less` type. I'm proposing solution for this here: #35 

In any way, currently implemented solution is really nice and flexible. Thank you!
