### ISSUE TITLE
Taglib: Add support for optimizer-* attributes to simplify how optimized resource URLs can be used in templates

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/optimizer#35]
Example usage:

Input:

```html
<link rel="shortcut icon" optimizer-href="./favicon.ico">
<img optimizer-src="./image.png">
```

Output:

```html
<link rel="shortcut icon" href="/static/favicon-a46d0c.ico">
<img src="/static/image-abc123.png">
```

Currently, the following is supported to accomplish the same thing, but it requires more code:

Input:

```html
<optimizer-resource path="./favicon.ico" var="favicon"/>
<optimizer-resource path="./image.png" var="someImage"/>

<link rel="shortcut icon" href="${favicon.url}">
<img src="${someImage.url}">
```

Output:

```html
<link rel="shortcut icon" href="/static/favicon-a46d0c.ico">
<img src="/static/image-abc123.png">
```
See #34 for further discussion.

**Comment by philidem** [comment]
I'm not really a big supporter of implementing this because I think there might be other uses for `optimizer-*` attributes other than getting the path to a resource.

**Comment by schetnikovich** [comment]
@philidem, I also agree, that `optimizer-*` "namespace" should not be used for this. Maybe it is better to use `resource-*` namespace. I'm also not a big supporter of this feature, but if we already have this ticket, I'll propose some unambiguous solution simply for history :)

In the simplest form, it can look like the following:
```html
<link resource-href="./favicon.ico">
```

If we want to specify some params for this resource, we can do the following:
```html
<link resource-href="./favicon.ico" resource-href-type="ico">
```
In the snippet above we specified `type` param for `href` resource. We also can specify multiple params:

```html
<link resource-href="./favicon.ico" resource-href-type="ico" resource-href-var="favicon">
```

This notation allows us to support multiple resource attributes and their params (although I don't know about HTML tag that allows to specify multiple resource attributes):

```html
<link 
    resource-href="./favicon.ico" resource-href-type="ico"  
    resource-src="./image.png" resource-src-type="png">
```
---
In previous ticket #34, @patrick-steele-idem mentioned reasons of why we need special `<optimizer-img />` tag, instead of `resource-*` attributes. But I come to conclusion, that even if we want to automatically generate `width` and `height` attributes, we also need a way to turn this feature on or off. This will introduce some special attribute to `<optimizer-img />` tag. We can select name for this attribute that is  not possible for `<img />` tag _today_, or we can use `optimizer-` prefix for it, to distinguish from HTML attributes, like the following:

```html
<optimizer-img src="./image.png" optimizer-dimensions="yes" />
```
If we'll use `dimensions` attribute, we create some small confusion for the user, because she now needs to distinguish between HTML attributes for `<img />` tag and attributes for `<optimizer-img />` tag:

```html
<optimizer-img src="./image.png" class="thumbnail" dimensions="no" />
```

So some confusions are unavoidable. In order to support `dimensions` param for `image` resources, we can also write:

```html
<img resource-src="./image.png" resource-src-dimensions="no" />
```
In the snippet above, `resource-src-type` is automatically determined as `image`, because of extension in the resource path.

This is simply my thoughts and desire to support HTML-first approach, when you are utilizing HTML tags and decorate them with some special attributes, instead of introducing special tags.

In my opinion it is also aligned well with Marko philosophy. In Marko we can write:
```html
<li for="item in items">${item}</li>
```

But you always allowed to use the full form:
```html
<for each="item in items">
    <li>${item}</li>
</for>
```
Last snippet is logically equivalent to the `<optimizer-resource />` tag that we already have in usability and flexibility (it allows to repeat some text when we do not have wrapper tag).

This is was a post for history. It is not an issue, it is a proposal for next couple of years :)

**Comment by philidem** [comment]
@schetnikovich, thanks for thinking about this some more. I think generally we all agree that we should be careful about introducing a lot of special attributes that create a new "language".

I think what @patrick-steele-idem did for finding the path of a resource is extremely helpful and I'm going to start using it in my projects right away. The only gap right now is the ability to read image width and height (and maybe other metadata if you want to get fancy). I like the idea of introducing a variable that contains the information (similar to `optimizer-resource`).

I opened #36 which contains two proposals which we can discuss as well. I am in favor of **OPTION 2**.

**Comment by schetnikovich** [comment]
@philidem, I agree that my proposal with special attributes feels like a new "language". And this side of proposal also doesn't make me happy :)

I propose to mark this issue with "controversial" tag and close it. Thank you both for your valuable time and thanks again for `<optimizer-resource />` tag!

**Comment by patrick-steele-idem** [comment]
I agree with your conclusions, @schetnikovich, and will go ahead and close this issue. Glad the `<optimizer-resource />` tag worked out for you. I do think issue #36 (Option 1) is worth implementing to better support the use case of getting access to an image's width and height inside a template.
